export const TRIPS_LIST_REQUEST = "TRIPS_LIST_REQUEST";
export const TRIPS_LIST_SUCCESS = "TRIPS_LIST_SUCCESS";
export const TRIPS_LIST_FAIL = "TRIPS_LIST_FAIL";

export const TRIPS_DETAILS_REQUEST = "TRIPS_DETAILS_REQUEST";
export const TRIPS_DETAILS_SUCCESS = "TRIPS_DETAILS_SUCCESS";
export const TRIPS_DETAILS_FAIL = "TRIPS_DETAILS_FAIL";

export const TRIPS_LIST_MY_RESET = "TRIPS_LIST_MY_RESET";
